title: Games are the Mother of Innovation
author: Nina Kilbride
email: 
description: >-
  How games drive social change

social:
  twitter: 
  facebook: 
  instagram: 
  github: 
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
