title: Buzzed Bunnies
author: Doc_Inks
email: 
description: >-
  A Collection of Buzzed, Baked and Bewildered Bunnies 


social:
  twitter:
  facebook: 
  instagram: @Doc_Inks
  github: 
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
